### ISSUE TITLE
为什么我使用hug得到的响应是unicode编码

### ISSUE THREAD

**Issue by junhuihuang** [wwj718/wechat_bot#1]
你好！我使用hug运行你的bot_api.py时，无法正确显示中文，显示的是unicode。

请问是什么原因？

谢谢~

**Comment by junhuihuang** [comment]
是否需要重新实现default output format？

**Comment by wwj718** [comment]
我这边正常的啊

![image](https://cloud.githubusercontent.com/assets/3153878/18334130/98089d12-75a7-11e6-8fd8-67808b854aba.png)

![image](https://cloud.githubusercontent.com/assets/3153878/18334178/027a6f54-75a8-11e6-8523-483f44849b70.png)

**Comment by junhuihuang** [comment]
奇怪了~
![image](https://cloud.githubusercontent.com/assets/1772676/18334431/ef36c76a-75a9-11e6-8ee7-591bd5c1d10b.png)

![image](https://cloud.githubusercontent.com/assets/1772676/18334445/0613a80e-75aa-11e6-839e-e4bc03fd28db.png)

正在用的hug版本是2.1.2，换成2.0.6也是如此。

**Comment by wwj718** [comment]
我是`hug==2.1.2`呢, 可能是chatterbot的缘故

**Comment by wwj718** [comment]
我刚添加了具体依赖，你是在python3下吗

**Comment by junhuihuang** [comment]
需要增加修饰器才能正常显示

@hug.default_output_format()
def my_output_formatter(data):
    return str(data).encode('utf8')

**Comment by wwj718** [comment]
👍
